# -*- coding: utf-8 -*-
from . import abstracts
from . import res_partner
from . import hr_contract
from . import onsc_cv_documentary_validation_config
from . import onsc_cv_digital
from . import onsc_cv_digital_call
from . import hr_employee
from . import onsc_cv_work_experience
from . import onsc_legajo
from . import onsc_legajo_alta_vl
from . import oncs_legajo_baja_vl
from . import onsc_cv_digital_vacante
from . import onsc_legajo_mass_upload_alta_vl
from . import onsc_legajo_alta_cs
from . import oncs_legajo_staging_ws7
from . import legajo_info
from . import onsc_legajo_report_config
from . import onsc_cv_settings
