# -*- coding: utf-8 -*-

from . import abstracts
from . import catalogs
from . import hr_department
from . import hr_employee
from . import res_company
from . import res_users
from . import res_users_role
from . import onsc_legajo_settings
from . import hr_job
from . import hr_contract
from . import onsc_legajo
from . import ir_attachment
from . import onsc_legajo_alta_vl
from . import oncs_legajo_baja_vl
from . import oncs_legajo_baja_cs
from . import oncs_legajo_alta_cs
from . import oncs_legajo_cambio_uo
from . import oncs_legajo_role_assignment
from . import oncs_legajo_staging_ws7
from . import onsc_legajo_declaration_law
from . import onsc_legajo_judicial_antecedents
from . import onsc_legajo_other_information
from . import onsc_legajo_merito
from . import onsc_legajo_demerito
from . import onsc_legajo_vote_control
from . import oncs_legajo_mass_cambio_uo
from . import views
from . import onsc_legajo_summary
