image: python:3.7
stages:
  - test

#services:
#  - postgres:10

variables:
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_DB: project_ci_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
#  EXCLUDE: "base_technical_features,custom_tree_view,url_access_restriction"
  TEST_DBNAME: '${CI_PROJECT_PATH_SLUG}-pipeline-${CI_PIPELINE_ID}'
  DEPLOY_DBNAME: '${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG}'
  RUNNER_HOME: '/home/gitlab-runner'
  INSTANCE_PATH: '${RUNNER_HOME}/instances/${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG}'
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  VERSION: "15.0"
  ODOO_BRANCH: "15.0"
  ODOO_REPO: "odoo/odoo"


before_script:
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y  sudo postgresql-client expect-dev nodejs python-dev python3-pip build-essential libsasl2-dev libldap2-dev libssl-dev libxml2-dev libxslt1-dev
  - pip3 install coverage coveralls codecov pylint six

lint:
  stage: test
  tags:
    - lint
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    # We need to export the PG* here, otherwise the postgresql container
    # Wil pick them up
    - export PGHOST="postgres"
    - export PGUSER="postgres"
    - export PGPASSWORD=""
    - git clone https://github.com/OCA/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - pip3 install --upgrade -r ${HOME}/maintainer-quality-tools/requirements.txt
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
    - sed -i '/^ignore =/ s/$/,E501,C8202,C8103/' ${HOME}/maintainer-quality-tools/travis/cfg/travis_run_flake8.cfg
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true

#test:
#  stage: test
#  tags:
#    - odoo
#    - test
#  variables:
#    LINT_CHECK: "0"
#    TESTS: "1"
#  script:
#    # We need to export the PG* here, otherwise the postgresql container
#    # Wil pick them up
#    - export PGHOST="postgres"
#    - export PGUSER="postgres"
#    - export PGPASSWORD=""
#    - export HOME="/oca"
#    - mkdir -p ${HOME}
#    #   adapt patch to sec-wall library
#    - git clone https://gitlab.quanam.com/quanam/sec-wall.git -b master ${HOME}/sec-wall
#    # - git clone https://github.com/flomincucci/sec-wall.git -b master ${HOME}/sec-wall
#    - cd ${HOME} && cd sec-wall
#    - python setup.py install --user
#    - git clone https://github.com/OCA/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
#    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
#    - psql -c 'CREATE ROLE odoo SUPERUSER LOGIN;'
#    - export PGUSER="odoo"
#    - travis_install_nightly
#    - travis_run_tests
#    - travis_after_tests_success || true
#  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
