# -*- coding: utf-8 -*-
{
    'name': 'ONSC - Legajo',
    'version': '15.0.28.8.0',
    'summary': 'ONSC - Legajo',
    'sequence': 11,
    'description': """
ONSC - Legajo
====================
    """,
    'category': 'ONSC',
    'depends': ['onsc_base',
                'onsc_catalog',
                'ws_int_base',
                'base_user_role',
                'base_user_role_hide_admin',
                'hr_contract',
                'model_history',
                'switch_jobs_security',
                'web_tree_header_buttons_always_visible'
                ],
    "data": [
        "security/onsc_legajo_security.xml",
        "security/ir.model.access.csv",
        "data/ir_filters_data.xml",
        "data/ir_cron_data.xml",
        "data/ir_config_parameters_data.xml",
        "data/onsc_legajo_state_square_data.xml",
        "data/onsc_legajo_reason_extinction_commission_data.xml",
        "data/onsc_legajo_commission_regime_data.xml",
        "data/onsc_legajo_integration_error_data.xml",
        "data/mail_template_data.xml",
        "data/onsc_legajo_role_electoral_act_data.xml",
        "data/onsc_legajo_data.xml",
        "wizard/mail_wizard_invite_views.xml",
        "wizard/onsc_legajo_padron_estructure_filter_wizard.xml",
        "wizard/onsc_legajo_movements_person_filter_wizard.xml",
        "wizard/onsc_legajo_other_movements_filter_wizard.xml",
        "views/onsc_legajo_department_views.xml",
        "views/onsc_legajo_padron_views.xml",
        "views/onsc_legajo_padron_movements_views.xml",
        "views/onsc_legajo_vote_registry_pending.xml",
        "views/onsc_legajo_settings_view.xml",
        "views/catalogs/onsc_catalog_descriptors.xml",
        "views/catalogs/onsc_legajo_emergency_views.xml",
        "views/catalogs/onsc_legajo_health_provider_views.xml",
        "views/catalogs/onsc_legajo_document_type_views.xml",
        "views/catalogs/onsc_legajo_income_mechanism_views.xml",
        "views/catalogs/onsc_legajo_causes_discharge_views.xml",
        "views/catalogs/onsc_legajo_integration_error_views.xml",
        "views/catalogs/onsc_legajo_reason_extinction_commission_views.xml",
        "views/catalogs/onsc_legajo_commission_regime_views.xml",
        "views/catalogs/onsc_legajo_state_square_views.xml",
        "views/catalogs/onsc_legajo_commission_regime_views.xml",
        "views/catalogs/onsc_legajo_security_job_views.xml",
        "views/catalogs/onsc_legajo_base_views.xml",
        "views/catalogs/onsc_catalog_electoral_act.xml",
        "views/catalogs/onsc_catalog_type_sanction.xml",
        "views/catalogs/onsc_catalog_legend.xml",
        "views/catalogs/onsc_catalog_res_country_department.xml",
        "views/catalogs/onsc_legajo_penalty_type_views.xml",
        "wizard/onsc_legajo_update_occupation_wizard_views.xml",
        "views/hr_employee_views.xml",
        "views/onsc_legajo_alta_vl_views.xml",
        "views/onsc_legajo_baja_vl_views.xml",
        "views/onsc_legajo_baja_cs_views.xml",
        "views/res_user_role_views.xml",
        "views/hr_job_views.xml",
        "views/hr_contract_views.xml",
        "views/onsc_legajo_views.xml",
        "views/onsc_legajo_other_views.xml",
        "views/onsc_legajo_vote_control_views.xml",
        "views/ir_attachment_view.xml",
        "views/onsc_legajo_alta_cs_view.xml",
        "views/onsc_legajo_cambio_uo_views.xml",
        "views/onsc_legajo_role_asignment_views.xml",
        "views/onsc_legajo_staging_ws7_views.xml",
        "wizard/onsc_legajo_sycronize_ws7_wizard_views.xml",
        "views/onsc_legajo_mass_cambio_uo_views.xml",
        "views/onsc_legajo_summary_views.xml",
        "views/onsc_legajo_menuitems.xml",
        "views/hr_contract_transaction_history_views.xml",
        "views/onsc_legajo_change_uo_movements_views.xml",
        "views/onsc_legajo_person_movements_views.xml",
        "views/onsc_legajo_other_movements_views.xml"
    ],
    'assets': {
        'web.assets_backend': [
            'onsc_legajo/static/src/js/basic_view.js',
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
