# -*- coding: utf-8 -*-
{
    'name': 'ONSC - Legajo',
    'version': '15.0.6.0.0',
    'summary': 'ONSC - Legajo',
    'sequence': 11,
    'description': """
ONSC - Legajo
====================
    """,
    'category': 'ONSC',
    'depends': ['onsc_base',
                'onsc_catalog',
                'base_user_role',
                'base_user_role_hide_admin',
                'hr_contract',
                'model_history',
                'switch_jobs_security'
                ],
    'data': [
        'security/onsc_legajo_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/ir_config_parameters_data.xml',
        'data/onsc_legajo_state_square_data.xml',
        'data/onsc_legajo_reason_extinction_commission_data.xml',
        'data/onsc_legajo_commission_regime_data.xml',
        'data/onsc_legajo_integration_error_data.xml',
        'views/catalogs/onsc_legajo_emergency_views.xml',
        'views/catalogs/onsc_legajo_health_provider_views.xml',
        'views/catalogs/onsc_legajo_document_type_views.xml',
        'views/catalogs/onsc_legajo_income_mechanism_views.xml',
        'views/catalogs/onsc_legajo_causes_discharge_views.xml',
        'views/catalogs/onsc_legajo_integration_error_views.xml',
        'views/catalogs/onsc_legajo_reason_extinction_commission_views.xml',
        'views/catalogs/onsc_legajo_commission_regime_views.xml',
        'views/catalogs/onsc_legajo_state_square_views.xml',
        'views/catalogs/onsc_legajo_commission_regime_views.xml',
        'views/catalogs/onsc_legajo_security_job_views.xml',
        'views/catalogs/onsc_legajo_base_views.xml',
        'wizard/onsc_legajo_update_occupation_wizard_views.xml',
        'views/hr_employee_views.xml',
        'views/onsc_legajo_alta_vl_views.xml',
        'views/onsc_legajo_baja_vl_views.xml',
        'views/res_user_role_views.xml',
        'views/hr_job_views.xml',
        'views/hr_contract_views.xml',
        'views/onsc_legajo_views.xml',
        'views/onsc_legajo_menuitems.xml',
        'views/ir_attachment_view.xml',

    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
