# -*- coding: utf-8 -*-
{
    'name': 'ONSC CV Digital',
    'version': '15.0.8.9.2',
    'summary': 'ONSC CV Digital',
    'sequence': 10,
    'description': """
ONSC CV Digital
====================
    """,
    'category': 'ONSC',
    # TODO report_context adicionado en su version 14 OCA no lo ha subido a 15 todavia
    'depends': ['base', 'web', 'mail', 'web_domain_field', 'phone_validation', 'onsc_base',
                'web_relational_field_with_create_edit_option', 'auto_save_form_view', 'disable_form_quick_edit',
                'model_history', 'ws_int_base', 'jsonifier', 'base_user_role_hide_admin', 'report_context',
                'auth_oauth', 'base_time_window'],
    'data': [
        'security/onsc_cv_digital_security.xml',
        'security/onsc_cv_digital_rules.xml',
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_config_parameters_data.xml',
        'data/onsc_cv_civil_status_data.xml',
        'data/onsc_cv_drivers_license_categories_data.xml',
        'data/onsc_cv_gender_data.xml',
        'data/onsc_cv_race_data.xml',
        'data/onsc_cv_experience_hierarchical_level_data.xml',
        'data/onsc_cv_study_level_data.xml',
        'data/onsc_cv_subtypes_data.xml',
        'data/onsc_cv_type_tutor_data.xml',
        'data/onsc_cv_type_orientation_data.xml',
        'data/onsc_cv_divulgation_media_data.xml',
        'data/onsc_cv_research_types_classes_data.xml',
        'data/onsc_cv_type_event_data.xml',
        'data/onsc_cv_type_support_data.xml',
        'data/onsc_cv_roll_event_data.xml',
        'data/onsc_cv_report_config_data.xml',
        'data/report_paperformat_data.xml',
        'data/res_user_role_data.xml',
        'data/onsc_cv_digital_data.xml',
        'wizard/views/onsc_cv_reject_wizard_views.xml',
        'wizard/views/onsc_cv_report_wizard_views.xml',
        'views/auth_oauth_templates.xml',
        'views/res_config_settings_view.xml',
        'views/onsc_cv_settings_view.xml',
        'views/onsc_cv_documentary_validation_config_views.xml',
        'views/catalogs/onsc_cv_document_type_views.xml',
        'views/catalogs/onsc_cv_civil_status_views.xml',
        'views/catalogs/onsc_cv_drivers_license_categories_views.xml',
        'views/catalogs/onsc_cv_gender_views.xml',
        'views/catalogs/onsc_cv_race_views.xml',
        'views/catalogs/onsc_cv_study_level_views.xml',
        'views/catalogs/onsc_cv_location_views.xml',
        'views/catalogs/res_country_views.xml',
        'views/catalogs/onsc_cv_subinstitution_views.xml',
        'views/catalogs/onsc_cv_institution_views.xml',
        'views/catalogs/onsc_cv_academic_program_views.xml',
        'views/catalogs/onsc_cv_certifying_institution_views.xml',
        'views/catalogs/onsc_cv_certifying_subinstitution_views.xml',
        'views/catalogs/onsc_cv_certificate_views.xml',
        'views/catalogs/onsc_cv_educational_areas_views.xml',
        'views/catalogs/onsc_cv_experience_hierarchical_level_views.xml',
        'views/catalogs/onsc_cv_educational_subarea_views.xml',
        'views/catalogs/onsc_cv_discipline_educational_views.xml',
        'views/catalogs/onsc_cv_knowledge_views.xml',
        'views/catalogs/onsc_cv_key_task_views.xml',
        'views/catalogs/onsc_cv_work_area_views.xml',
        'views/catalogs/onsc_cv_entry_views.xml',
        'views/catalogs/onsc_cv_professional_link_views.xml',
        'views/catalogs/onsc_cv_subtype_evaluation_views.xml',
        'views/catalogs/onsc_cv_subtype_other_views.xml',
        'views/catalogs/onsc_cv_subtype_production_views.xml',
        'views/catalogs/onsc_cv_subtype_publication_views.xml',
        'views/catalogs/onsc_cv_type_orientation_views.xml',
        'views/catalogs/onsc_cv_type_tutor_views.xml',
        'views/catalogs/onsc_cv_research_types_classes_views.xml',
        'views/catalogs/onsc_cv_language_views.xml',
        'views/catalogs/onsc_cv_type_support_views.xml',
        'views/catalogs/onsc_cv_type_event_views.xml',
        'views/catalogs/onsc_cv_roll_event_views.xml',
        'views/catalogs/onsc_cv_divulgation_media_views.xml',
        'views/catalogs/res_partner_views.xml',
        'views/catalogs/onsc_cv_street_views.xml',
        'views/catalogs/onsc_cv_generic_academic_program_views.xml',
        'views/onsc_cv_course_certificate_views.xml',
        'views/onsc_cv_formation_views.xml',
        'views/onsc_cv_digital_views.xml',
        'views/onsc_cv_digital_work_experience_views.xml',
        'views/onsc_cv_work_teaching_views.xml',
        'views/onsc_cv_work_investigation_views.xml',
        'views/onsc_cv_digital_volunteering_views.xml',
        'views/onsc_cv_language_level_views.xml',
        'views/cv_digital_publications_productions_evaluations_views.xml',
        'views/onsc_cv_tutoring_orientation_supervision_views.xml',
        'views/onsc_cv_digital_participation_events_views.xml',
        'views/onsc_cv_digital_refernece_views.xml',
        'views/onsc_cv_digital_drive_licence.xml',
        'views/onsc_cv_digital_call_views.xml',
        'views/onsc_cv_digital_call_documentary_validation_views.xml',
        'views/onsc_cv_report_config_views.xml',
        'views/onsc_cv_menuitems.xml',
        'report/onsc_cv_digital_report.xml',
    ],
    'demo': [
        'demo/onsc_cv_demo.xml',
        'demo/res_partner_demo.xml',
    ],
    'external_dependencies': {
        'python': ['zeep', 'basicauth', 'spyne', 'json'],
    },
    'assets': {
        'web.assets_backend': [
            'onsc_cv_digital/static/src/js/form_renderer.js',
        ],
        'web.report_assets_common': [
            'onsc_cv_digital/static/src/css/style.css',
        ],
        'web.assets_qweb': [
            'onsc_cv_digital/static/src/xml/*.xml',
        ],
    },

    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
