# -*- coding: utf-8 -*-
{
    'name': 'ONSC CV Digital',
    'version': '15.0.2.0.0.',
    'summary': 'ONSC CV Digital',
    'sequence': 10,
    'description': """
ONSC CV Digital
====================
    """,
    'category': 'ONSC',
    'depends': ['base', 'mail', 'web_domain_field'],
    'data': [
        'security/onsc_cv_digital_security.xml',
        'security/onsc_cv_digital_rules.xml',
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'data/onsc_cv_civil_status_data.xml',
        'data/onsc_cv_drivers_license_categories_data.xml',
        'data/onsc_cv_gender_data.xml',
        'data/onsc_cv_race_data.xml',
        'data/onsc_cv_experience_hierarchical_level_data.xml',
        'data/onsc_cv_study_level_data.xml',
        'data/onsc_cv_subtypes_data.xml',
        'data/onsc_cv_type_tutor_data.xml',
        'data/onsc_cv_type_orientation_data.xml',
        'data/onsc_cv_divulgation_media_data.xml',
        'data/onsc_cv_research_types_classes_data.xml',
        'data/onsc_cv_type_event_data.xml',
        'data/onsc_cv_type_support_data.xml',
        'data/onsc_cv_roll_event_data.xml',
        'wizard/views/onsc_cv_reject_wizard_views.xml',
        'views/res_config_settings_view.xml',
        'views/catalogs/onsc_cv_document_type_views.xml',
        'views/catalogs/onsc_cv_civil_status_views.xml',
        'views/catalogs/onsc_cv_drivers_license_categories_views.xml',
        'views/catalogs/onsc_cv_gender_views.xml',
        'views/catalogs/onsc_cv_race_views.xml',
        'views/catalogs/onsc_cv_study_level_views.xml',
        'views/catalogs/onsc_cv_location_views.xml',
        'views/catalogs/res_country_views.xml',
        'views/catalogs/onsc_cv_subinstitution_views.xml',
        'views/catalogs/onsc_cv_institution_views.xml',
        'views/catalogs/onsc_cv_academic_program_views.xml',
        'views/catalogs/onsc_cv_certifying_institution_views.xml',
        'views/catalogs/onsc_cv_certifying_subinstitution_views.xml',
        'views/catalogs/onsc_cv_certificate_views.xml',
        'views/catalogs/onsc_cv_educational_areas_views.xml',
        'views/catalogs/onsc_cv_experience_hierarchical_level_views.xml',
        'views/catalogs/onsc_cv_educational_subarea_views.xml',
        'views/catalogs/onsc_cv_discipline_educational_views.xml',
        'views/catalogs/onsc_cv_knowledge_views.xml',
        'views/catalogs/onsc_cv_key_task_views.xml',
        'views/catalogs/onsc_cv_work_area_views.xml',
        'views/catalogs/onsc_cv_entry_views.xml',
        'views/catalogs/onsc_cv_professional_link_views.xml',
        'views/catalogs/onsc_cv_subtype_evaluation_views.xml',
        'views/catalogs/onsc_cv_subtype_other_views.xml',
        'views/catalogs/onsc_cv_subtype_production_views.xml',
        'views/catalogs/onsc_cv_subtype_publication_views.xml',
        'views/catalogs/onsc_cv_type_orientation_views.xml',
        'views/catalogs/onsc_cv_type_tutor_views.xml',
        'views/catalogs/onsc_cv_research_types_classes_views.xml',
        'views/catalogs/onsc_cv_language_views.xml',
        'views/catalogs/onsc_cv_type_support_views.xml',
        'views/catalogs/onsc_cv_type_event_views.xml',
        'views/catalogs/onsc_cv_roll_event_views.xml',
        'views/catalogs/onsc_cv_divulgation_media_views.xml',
        'views/catalogs/res_partner_views.xml',
        'views/onsc_cv_course_certificate_views.xml',
        'views/onsc_cv_formation_views.xml',
        'views/onsc_cv_digital_views.xml',
        'views/onsc_cv_digital_work_experience_views.xml',
        'views/onsc_cv_menuitems.xml',
    ],
    'demo': [
        'demo/onsc_cv_demo.xml',
        'demo/res_partner_demo.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
