# -*- coding: utf-8 -*-
from . import res_company
from . import res_users
from . import catalogs
from . import hr_job
from . import oncs_legajo_role_assignment
from . import oncs_legajo_cambio_uo
from . import onsc_desempeno_score
from . import onsc_desempeno_general_cycle
from . import onsc_desempeno_settings
from . import onsc_desempeno_evaluation_stage
from . import onsc_desempeno_evaluation_list
from . import onsc_desempeno_evaluation
from . import onsc_desempeno_evaluation_competency
from . import onsc_desempeno_consolidated
from . import onsc_desempeno_evaluation_development_means
from . import onsc_desempeno_summary_evaluation
from . import onsc_desempeno_evaluation_report
from . import onsc_legajo
from . import oncs_legajo_staging_ws7
from . import onsc_desempeno_competency_skills
