# -*- coding: utf-8 -*-
{
    'name': 'ONSC CV Digital - Legajo',
    'version': '15.0.27.0.0',
    'summary': 'ONSC CV Digital - Legajo',
    'sequence': 11,
    'description': """
ONSC CV Digital - Legajo
====================
    """,
    'category': 'ONSC',
    'depends': ['onsc_cv_digital', 'hr', 'onsc_legajo', 'onsc_cv_digital_catalog'],
    'data': [
        'security/onsc_cv_digital_legajo_security.xml',
        'security/onsc_cv_digital_legajo_rules.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/ir_config_parameters_data.xml',
        'data/ir_cron_data.xml',
        'data/onsc_legajo_report_config_data.xml',
        'data/report_paperformat_data.xml',
        'wizard/views/onsc_legajo_report_wizard_views.xml',
        'views/res_partner_views.xml',
        'views/onsc_cv_documentary_validation_config_views.xml',
        'views/onsc_cv_digital_views.xml',
        'views/onsc_cv_hr_employee_views.xml',
        'views/onsc_cv_work_experience_views.xml',
        'views/onsc_cv_digital_validation_views.xml',
        'views/legajo_info/onsc_legajo_work_experience_views.xml',
        'views/legajo_info/onsc_legajo_tutoring_orientation_supervision_views.xml',
        'views/legajo_info/onsc_legajo_volunteering_views.xml',
        'views/legajo_info/onsc_legajo_work_teaching_views.xml',
        'views/legajo_info/onsc_legajo_participation_events_views.xml',
        'views/legajo_info/onsc_legajo_work_investigation_views.xml',
        'views/legajo_info/onsc_legajo_publications_productions_evaluations_views.xml',
        'views/legajo_info/onsc_legajo_other_relevant_information_views.xml',
        'views/legajo_info/onsc_legajo_formation_views.xml',
        'views/legajo_info/onsc_legajo_course_views.xml',
        'views/onsc_cv_other_relevant_information_views.xml',
        'views/onsc_legajo_views.xml',
        'views/onsc_legajo_alta_vl_views.xml',
        'views/onsc_legajo_mass_upload_alta_vl.xml',
        'views/onsc_legajo_alta_cs_view.xml',
        'views/onsc_legajo_report_config_views.xml',
        'views/onsc_cv_digital_legajo_menuitems.xml',
        'views/onsc_cv_settings_view.xml',
        'views/onsc_cv_minimal_views.xml',
        # REPORTE LEGAJO
        'report/onsc_cv_digital_report.xml',
        'report/legajo_report_sections/onsc_legajo_report_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_section_funct_info.xml',
        'report/legajo_report_sections/onsc_legajo_report_formation_course_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_work_experince_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_teaching_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_investigation_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_volunteering_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_tos_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_section_ppe.xml',
        'report/legajo_report_sections/onsc_legajo_report_other_relevant_information_sections.xml',
        'report/legajo_report_sections/onsc_legajo_report_events_sections.xml',
        'report/onsc_legajo_report.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
